### ISSUE TITLE
I can't simulate a spam result

### ISSUE THREAD

**Issue by alehandrof** [edalzell/statamic-akismet#2]
I believe I've set up Akismet correctly, but I can't catch any spam. Here's a form submission that doesn't get caught as spam:

```
contact__name: viagra-test-123
contact__email: akismet-guaranteed-spam@example.com
contact__message: 'Test, test, test.'
```

Both the name and email use the triggers that [Akismet's API docs](https://akismet.com/development/api/#detailed-docs) state will simulate a spam result.

Can you please confirm whether this submission works on your end?

**Comment by edalzell** [comment]
Can you please share the addon settings and the template form code?

**Comment by edalzell** [comment]
<img width="753" alt="2018-08-27 at 7 33 pm" src="https://user-images.githubusercontent.com/6069653/44697407-756c8b00-aa30-11e8-85f5-e4d9fc23a33f.png">

**Comment by alehandrof** [comment]
Hmm. I suspect that Akismet might be ignoring my development domain. I'll come back to you if the problem persists on my staging server. Feel free to close the issue in the meantime.

**Comment by alehandrof** [comment]
### Addon settings

```
akismet_key: %% key %%
roles:
  - 6414c825-9b31-4ec6-a49a-8ef8c5321621
forms:
  -
    form_and_fields:
      form: profile-email
      author_field: contact__name
      email_field: contact__email
      content_field: contact__message
  -
    form_and_fields:
      form: profile-email
      author_field: contact__name
      email_field: contact__email
      content_field: contact__message
```

### Contact fieldset

```
title: Contact
honeypot: sweetraven
fields:
  contact__name:
    display: Name
    validate: required
  contact__email:
    display: Email
    validate: required|email
  contact__message:
    display: Message
    validate: required
columns:
  - contact__name
  - contact__email
  - contact__message
email:
  -
    to: %% Organizational email %%
    from: '{{ contact__email }}'
    subject: "Message from {{ contact__name }}"
    template: contact
```

The form template itself is pretty complex. Are you sure you need it?
